# Generated by Django 3.2.3 on 2021-06-20 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuals', '0003_alter_serie_books_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название книги')),
                ('foto', models.BinaryField(verbose_name='Фото обложки')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('year', models.IntegerField(verbose_name='Год издания')),
                ('pages', models.IntegerField(verbose_name='Количество страниц')),
                ('binding', models.TextField(verbose_name='Переплет')),
                ('format', models.TextField(verbose_name='Формат')),
                ('isbn', models.IntegerField(max_length=15, verbose_name='ISBN')),
                ('weight', models.IntegerField(verbose_name='Вес книги')),
                ('age', models.TextField(verbose_name='Возрастные ограничения')),
                ('avail_quan', models.IntegerField(verbose_name='Количество книг в наличии')),
                ('active', models.BooleanField(default=False, verbose_name='Доступно для заказа')),
                ('rating', models.IntegerField(max_length=15, verbose_name='Рейтинг книги')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Краткое описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_books', to='manuals.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre_books', to='manuals.genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publisher_books', to='manuals.publisher')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serie_books', to='manuals.serie')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
