# Generated by Django 3.2.3 on 2021-06-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='age',
        ),
        migrations.AddField(
            model_name='book',
            name='age_rating',
            field=models.IntegerField(choices=[(None, '---'), (1, '0+'), (2, '6+'), (3, '12+'), (4, '16+'), (5, '18+')], default=None, verbose_name='Возрастные ограничения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='binding',
            field=models.IntegerField(choices=[(None, '---'), (1, 'Твердый переплет'), (2, 'Мягкий переплет')], default=None, verbose_name='Переплет'),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(max_length=300, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(choices=[(None, '---'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, verbose_name='Рейтинг книги'),
        ),
    ]
