# Generated by Django 3.2.3 on 2021-06-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210620_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='foto',
        ),
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(default='book_picture', upload_to='books/%Y/%m/%d/', verbose_name='Обложка книги'),
            preserve_default=False,
        ),
    ]
