# Generated by Django 3.2.3 on 2021-06-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0003_alter_serie_books_quantity'),
        ('books', '0010_auto_20210623_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='author_books', to='manuals.Author', verbose_name='Автор'),
        ),
    ]
