# Generated by Django 3.2.3 on 2021-06-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_bookincart_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookincart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2021-06-30', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookincart',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2021-06-30', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
