# Generated by Django 3.2.3 on 2021-06-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_bookincart_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookincart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2021-06-28', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookincart',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.TextField(verbose_name='Контактная инфорамация')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carts.cart', verbose_name='Заказ')),
            ],
        ),
    ]
