# Generated by Django 3.2.3 on 2021-07-01 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('postcode', models.IntegerField(verbose_name='Почтовый индекс')),
                ('address1', models.TextField(verbose_name='Адрес 1')),
                ('address2', models.TextField(default='---', verbose_name='Адрес 2')),
                ('addit_info', models.TextField(default='---', verbose_name='Дополнительная информация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт пользователя')),
            ],
        ),
    ]
