# Generated by Django 3.2.3 on 2021-05-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0002_alter_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='books_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество книг в серии'),
        ),
    ]
