# Generated by Django 3.2.3 on 2021-06-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0003_alter_serie_books_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=100, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
    ]
