# Generated by Django 3.2.3 on 2021-06-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_info',
            field=models.TextField(verbose_name='Контактная информация'),
        ),
    ]
