# Generated by Django 3.2.3 on 2021-07-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_alter_cart_customer'),
        ('orders', '0006_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='carts.cart', verbose_name='Заказ'),
        ),
    ]
